/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangTermsOfServiceRouteImport } from './routes/$lang/terms-of-service'
import { Route as LangPrivacyPolicyRouteImport } from './routes/$lang/privacy-policy'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as LangGuidesIndexRouteImport } from './routes/$lang/guides/index'
import { Route as LangGuidesSlugRouteImport } from './routes/$lang/guides/$slug'
import { Route as LangCategoryQuantityRouteImport } from './routes/$lang/category.$quantity'
import { Route as LangConvertQuantityFromToToRouteImport } from './routes/$lang/convert.$quantity.$from.to.$to'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangTermsOfServiceRoute = LangTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPrivacyPolicyRoute = LangPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangGuidesIndexRoute = LangGuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangGuidesSlugRoute = LangGuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCategoryQuantityRoute = LangCategoryQuantityRouteImport.update({
  id: '/category/$quantity',
  path: '/category/$quantity',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangConvertQuantityFromToToRoute =
  LangConvertQuantityFromToToRouteImport.update({
    id: '/convert/$quantity/$from/to/$to',
    path: '/convert/$quantity/$from/to/$to',
    getParentRoute: () => LangRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/privacy-policy': typeof LangPrivacyPolicyRoute
  '/$lang/terms-of-service': typeof LangTermsOfServiceRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/category/$quantity': typeof LangCategoryQuantityRoute
  '/$lang/guides/$slug': typeof LangGuidesSlugRoute
  '/$lang/guides/': typeof LangGuidesIndexRoute
  '/$lang/convert/$quantity/$from/to/$to': typeof LangConvertQuantityFromToToRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/privacy-policy': typeof LangPrivacyPolicyRoute
  '/$lang/terms-of-service': typeof LangTermsOfServiceRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/category/$quantity': typeof LangCategoryQuantityRoute
  '/$lang/guides/$slug': typeof LangGuidesSlugRoute
  '/$lang/guides': typeof LangGuidesIndexRoute
  '/$lang/convert/$quantity/$from/to/$to': typeof LangConvertQuantityFromToToRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/privacy-policy': typeof LangPrivacyPolicyRoute
  '/$lang/terms-of-service': typeof LangTermsOfServiceRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/category/$quantity': typeof LangCategoryQuantityRoute
  '/$lang/guides/$slug': typeof LangGuidesSlugRoute
  '/$lang/guides/': typeof LangGuidesIndexRoute
  '/$lang/convert/$quantity/$from/to/$to': typeof LangConvertQuantityFromToToRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/privacy-policy'
    | '/$lang/terms-of-service'
    | '/$lang/'
    | '/$lang/category/$quantity'
    | '/$lang/guides/$slug'
    | '/$lang/guides/'
    | '/$lang/convert/$quantity/$from/to/$to'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/privacy-policy'
    | '/$lang/terms-of-service'
    | '/$lang'
    | '/$lang/category/$quantity'
    | '/$lang/guides/$slug'
    | '/$lang/guides'
    | '/$lang/convert/$quantity/$from/to/$to'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/privacy-policy'
    | '/$lang/terms-of-service'
    | '/$lang/'
    | '/$lang/category/$quantity'
    | '/$lang/guides/$slug'
    | '/$lang/guides/'
    | '/$lang/convert/$quantity/$from/to/$to'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/terms-of-service': {
      id: '/$lang/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/$lang/terms-of-service'
      preLoaderRoute: typeof LangTermsOfServiceRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/privacy-policy': {
      id: '/$lang/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/$lang/privacy-policy'
      preLoaderRoute: typeof LangPrivacyPolicyRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/guides/': {
      id: '/$lang/guides/'
      path: '/guides'
      fullPath: '/$lang/guides/'
      preLoaderRoute: typeof LangGuidesIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/guides/$slug': {
      id: '/$lang/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/$lang/guides/$slug'
      preLoaderRoute: typeof LangGuidesSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/category/$quantity': {
      id: '/$lang/category/$quantity'
      path: '/category/$quantity'
      fullPath: '/$lang/category/$quantity'
      preLoaderRoute: typeof LangCategoryQuantityRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/convert/$quantity/$from/to/$to': {
      id: '/$lang/convert/$quantity/$from/to/$to'
      path: '/convert/$quantity/$from/to/$to'
      fullPath: '/$lang/convert/$quantity/$from/to/$to'
      preLoaderRoute: typeof LangConvertQuantityFromToToRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangContactRoute: typeof LangContactRoute
  LangPrivacyPolicyRoute: typeof LangPrivacyPolicyRoute
  LangTermsOfServiceRoute: typeof LangTermsOfServiceRoute
  LangIndexRoute: typeof LangIndexRoute
  LangCategoryQuantityRoute: typeof LangCategoryQuantityRoute
  LangGuidesSlugRoute: typeof LangGuidesSlugRoute
  LangGuidesIndexRoute: typeof LangGuidesIndexRoute
  LangConvertQuantityFromToToRoute: typeof LangConvertQuantityFromToToRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangContactRoute: LangContactRoute,
  LangPrivacyPolicyRoute: LangPrivacyPolicyRoute,
  LangTermsOfServiceRoute: LangTermsOfServiceRoute,
  LangIndexRoute: LangIndexRoute,
  LangCategoryQuantityRoute: LangCategoryQuantityRoute,
  LangGuidesSlugRoute: LangGuidesSlugRoute,
  LangGuidesIndexRoute: LangGuidesIndexRoute,
  LangConvertQuantityFromToToRoute: LangConvertQuantityFromToToRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
